title: "浩瀚星河"
paginate: 8         # 每页显示的文章条数
buildfuture: true   # 解决时区问题
relativeURLs: true

theme: hugo-stellar

markup:
  _merge: deep # 删除此项将导致代码块渲染异常
  tableOfContents: # 以下配置表明文章的目录将只包括 h1 ~ h4
    startLevel: 1
    endLevel: 4

params:
  author: 浩瀚星河
  avatar: /avatar.jpg
  logo: /avatar.jpg

  description:
  - "A Go Enthusiast"
  - "实习前的些许风霜罢了"

  notice: 本站是浩瀚星河的知识库和项目集合站，希望您在这里玩的开心。

  social:
  - name: "hugo"
    url: "https://gohugo.io/"
    logo: "/social/hugo.svg"
  - name: "github"
    url: "https://github.com/codepzj"
    logo: "/social/github.svg"
  - name: "bilibili"
    url: "https://www.bilibili.com/"
    logo: "/social/bilibili.svg"

menus:
  main:
  - name: "博客"
    weight: 1
    url: "/"
    params:
      tabs:
      - name: "所有文章"
        url: "/"
      - name: "分类"
        url: "/categories/"
      - name: "标签"
        url: "/tags/"
      - name: "归档"
        url: "/archives/"
  - name: "关于"
    weight: 2
    url: "/about/"
    params:
      tabs:
      - name: "关于本站"
        url: "/about/"
