name: deploy-hugo-site

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout Your Repository
        uses: actions/checkout@v4
        with:
          submodules: true  # 处理子模块
          
      # 更新子模块
      - name: Update submodules
        run: git submodule update --init --recursive

      # 安装Hugo CLI
      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.120.2/hugo_extended_0.120.2_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      # 安装Dart Sass
      - name: Install Dart Sass
        run: sudo snap install dart-sass

      # 设置 Hugo 环境变量
      - name: Set Environment Variables
        run: echo "HUGO_ENVIRONMENT=production" >> $GITHUB_ENV

      # 构建 Hugo 网站
      - name: Build Hugo Site
        run: |
          hugo --gc --minify

      # 复制构建的文件到服务器
      - name: Copy Dist Files with SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HUGO_HOST }}
          username: ${{ secrets.HUGO_USERNAME }}
          password: ${{ secrets.HUGO_PASSWORD }}
          port: ${{ secrets.HUGO_PORT }}
          source: "public/"
          target: ${{ secrets.HUGO_TARGET }}
